# Generated by Django 5.0 on 2023-12-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=200)),
                ('modele', models.CharField(max_length=200)),
                ('anneeConstruction', models.DateTimeField()),
                ('cylindree', models.IntegerField()),
                ('version', models.CharField(max_length=200)),
            ],
        ),
    ]
